# Generated by Django 4.0.1 on 2022-01-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_categoria', models.CharField(max_length=200, unique=True)),
                ('slug_categoria', models.SlugField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juegos_de_mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_juegos_de_mesa', models.CharField(max_length=200)),
                ('votacion', models.IntegerField(default=0)),
                ('body', models.CharField(max_length=255)),
                ('imagen_juegos_de_mesa', models.ImageField(null=True, upload_to=None)),
                ('slug_juegos_de_mesa', models.SlugField(max_length=255, null=True, unique=True)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padre', to='al_games.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Ofertas_juegos_de_mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('tienda', models.CharField(max_length=255)),
                ('juego_de_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='al_games.juegos_de_mesa')),
            ],
        ),
    ]
