# Generated by Django 4.0.1 on 2022-01-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0002_alter_juegos_de_mesa_imagen_juegos_de_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juegos_de_mesa',
            name='slug_juegos_de_mesa',
        ),
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
    ]
