# Generated by Django 4.0.1 on 2022-01-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0003_remove_juegos_de_mesa_slug_juegos_de_mesa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegos_de_mesa',
            old_name='slug',
            new_name='slug_juegos_de_mesa',
        ),
    ]
