# Generated by Django 4.0.1 on 2022-01-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0004_rename_slug_juegos_de_mesa_slug_juegos_de_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos_de_mesa',
            name='slug_juegos_de_mesa',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
