# Generated by Django 4.0.1 on 2022-01-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0005_alter_juegos_de_mesa_slug_juegos_de_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='slug_categoria',
        ),
        migrations.RemoveField(
            model_name='juegos_de_mesa',
            name='slug_juegos_de_mesa',
        ),
        migrations.AddField(
            model_name='categorias',
            name='slug',
            field=models.SlugField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='slug',
            field=models.SlugField(default='hola', max_length=255),
            preserve_default=False,
        ),
    ]
