# Generated by Django 4.0.1 on 2022-01-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0006_remove_categorias_slug_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='juegos_de_mesa',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
