# Generated by Django 4.0.1 on 2022-01-17 09:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0007_alter_categorias_slug_alter_juegos_de_mesa_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos_de_mesa',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
