# Generated by Django 4.0.1 on 2022-01-20 10:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0008_alter_juegos_de_mesa_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos_de_mesa',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='juegos_de_mesa',
            name='imagen_juegos_de_mesa',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='juegos_de_mesa',
            name='votacion',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
