# Generated by Django 4.0.1 on 2022-01-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0009_alter_juegos_de_mesa_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos_de_mesa',
            name='categorias',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='padre', to='al_games.categorias'),
        ),
    ]
