# Generated by Django 4.0.1 on 2022-01-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0010_alter_juegos_de_mesa_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='titulo_categoria',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
