# Generated by Django 4.0.1 on 2022-01-20 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0011_alter_categorias_titulo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='titulo_categoria',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='juegos_de_mesa',
            name='categorias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padre', to='al_games.categorias'),
        ),
    ]
