# Generated by Django 4.0.1 on 2022-01-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0014_alter_ofertas_juegos_de_mesa_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas_juegos_de_mesa',
            name='precio',
            field=models.CharField(max_length=255),
        ),
    ]
