# Generated by Django 4.0.1 on 2022-01-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0015_alter_ofertas_juegos_de_mesa_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos_de_mesa',
            name='votacion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
