# Generated by Django 4.0.1 on 2022-01-22 12:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0016_alter_juegos_de_mesa_votacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='body',
            field=ckeditor.fields.RichTextField(default='Hola'),
            preserve_default=False,
        ),
    ]
