# Generated by Django 4.0.1 on 2022-02-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0017_categorias_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='imagen_url',
            field=models.URLField(default='prueba.jpg'),
            preserve_default=False,
        ),
    ]
