# Generated by Django 4.0.1 on 2022-02-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0018_juegos_de_mesa_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas_juegos_de_mesa',
            name='precio',
            field=models.FloatField(max_length=255),
        ),
    ]
