# Generated by Django 4.0.1 on 2022-02-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0019_alter_ofertas_juegos_de_mesa_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas_juegos_de_mesa',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
