# Generated by Django 4.0.1 on 2022-03-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0021_ofertas_juegos_de_mesa_enlaces_tiendas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLibreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
