# Generated by Django 4.0.1 on 2022-03-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0022_medialibreria'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibreria',
            name='titulo_imagen',
            field=models.CharField(default='header', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
