# Generated by Django 4.0.1 on 2022-03-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0023_medialibreria_titulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='autores',
            field=models.CharField(default='Thomas Lehmann', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='duracion',
            field=models.CharField(default='10-15', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='publicacion',
            field=models.CharField(default='2015', max_length=255),
            preserve_default=False,
        ),
    ]
