# Generated by Django 4.0.1 on 2022-04-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0024_juegos_de_mesa_autores_juegos_de_mesa_duracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='titulo_seo',
            field=models.CharField(default='esto mola', max_length=255),
            preserve_default=False,
        ),
    ]
