# Generated by Django 4.0.1 on 2022-04-27 08:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('al_games', '0025_juegos_de_mesa_titulo_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_categoria_blog', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='juegos_de_mesa',
            name='description_seo',
            field=models.CharField(default='molados', max_length=155),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_seo', models.CharField(max_length=155)),
                ('description_seo', models.CharField(max_length=155)),
                ('titulo', models.CharField(max_length=255)),
                ('imagen_blog', models.ImageField(blank=True, null=True, upload_to='media')),
                ('cuerpo_articulo', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padre', to='al_games.categoriasblog')),
            ],
        ),
    ]
